baseURL = "https://blog.nsfisis.dev"
languageCode = "ja-JP"
hasCJKLanguage = true
timeZone = "Asia/Tokyo"
title = "REPL: Rest-Eat-Program Loop"
theme = "mypaper"

[author]
name = "nsfisis"

[taxonomies]
tag = "tags"

[outputFormats.rss]
baseName = "feed"
