version: '3'

services:
  blog_nsfisis_nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs:/public
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    restart: always
